server:
  port: 8000
#  ssl:
#    enabled: true
#    key-store:  src/main/resources/keystore.jks
#    key-store-password: 123456
#    key-password: 123456
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PORTFOLIO?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true

